### ISSUE TITLE
Change date-filtering control user interface

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape-issuemap#4]
I missed the date controls in the bottom-right. So I suggest changing this interface to something along the following lines:

- PerhapsHave the date-filtering controls as a third block of controls under the tags area
- Have a heading like 'Date:' or similar
- Set four checkboxes, one for each of the four legends
- Each legend would go next to its related checkbox
- By default include no Future deadline and No deadline

**Comment by georgio8** [comment]
Now implemented along the lines described above. It seems a much clearer and systematic approach.
