### ISSUE TITLE
Upcoming deadlines

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/cyclescape-issuemap#5]
At present, this appears to be a link that could take the user off-site. Accordingly, this may dissuade a user from clicking on it as they may assume that will lose their map position.

So I would use either:

- Some kind of checkbox, so that it's clear that this toggles a state in the existing interface
- A fold-down triangle type interface, that has a rotating triangle next to the heading, and when clicked folds down (or up) the panel.
- A free-floating button that toggles the panel on or off.

**Comment by georgio8** [comment]
I have an experimental implementation of a free-floating button for this but the tick box solution would give better UI consistency, and that should be grouped in the same pane with the tick boxes for the Date filtering #4 , on which work will commence soon.

**Comment by georgio8** [comment]
Now appears below the Map title, along with the link to the documentation.
